### PR TITLE
Add Node Requirement Support

### PR DESCRIPTION
**Pull request by pmyers88**
This proposal suggests adding support for Node Requirement (`depends_on
:node`) to the Formula DSL.

If this is something you want to do I'd happily submit a PR :).

### CODE REVIEW

**Comment by zmwangx** [comment]
Node installed from nvm is ephemeral (won't be able to available in another shell session without nvm loaded) and can vary wildly in version. Given the size and viralness of the Node.js community, many users probably don't understand their tooling well, and a lot of pointless support burden would arise due to this. So 👎 on this.

**Comment by zmwangx** [comment]
Brewed node is only 40M in size so I don't understand the concern.

**Comment by pmyers88** [comment]
The concern is that I prefer using nvm to manage my node versions and don't want to have an additional brewed node on my machine.

The Ruby community is comparable in size, viralness and misunderstanding of tooling, but brew doesn't force them to install brewed ruby versions unnecessarily. Why the difference?

**Comment by zmwangx** [comment]
The profound difference is there's `/usr/bin/ruby` but not `/usr/bin/node`.

**Comment by zmwangx** [comment]
Say we allow this `NodeRequirement`. Then the same can be requested for any language runtime (and more justifiably so for certain languages), and by extension any package that can be obtained via other means (read: all of them). The entire premise of brew breaks down.

**Comment by pmyers88** [comment]
The `RubyRequirement` code doesn't make a distinction for `/usr/bin/ruby`, it just looks for a matching ruby version on the `$PATH`.

I'm still having trouble understanding why it's bad to check the `$PATH` for node before installing brewed node, but it's good to check the `$PATH` for ruby before installing brewed ruby. If the user has a misconfigured path they're still going to get the brewed executable; I'm not sure of the downside to checking.

I don't think that adding another language runtime requirement to a list of existing language runtime requirements leads to a slippery slope of destroying the brew ecosystem.

I do understand the hesitancy to add a new feature, particularly one that's not critical/in high demand. I just wanted to create this PR since it's something @MikeMcQuaid mentioned in [#6187](https://github.com/Homebrew/homebrew-core/issues/6187) and it's something I would like to see.

**Comment by zmwangx** [comment]
In the case of Ruby or Perl, there's a `/usr/bin/` binary to fall back to, and installing the Homebrew formula (in `/usr/local` by default) would mask the system version, so there's a case to be made that users may want to use the system version. The requirements are written in a way that any binary on the path can satisfy the requirements, which is kind of unfortunate IMO, but at least you have something to fall back to in most cases.

In the case of Node, or anything not provided by macOS, it's very easy to have a different environment at run time than install time, and with shell-integrated language runtime version managers, it's especially easy to screw it up. A user may have nvm active when he was installing foo, then not have it later when he tries to run it, thus not having a runtime on PATH. Then, without sufficient knowledge of PATH (occurs surprisingly often), said user claims that it's Homebrew's fault.

If you really dislike the additional 40MB, `brew unlink node; rm -rf /usr/local/Cellar/node`, which should work even when we start to forbid uninstalling active dependencies. Problem solved.

**Comment by zmwangx** [comment]
In short, requirements should be reserved for situations when something is conditionally fulfilled by the system (ruby, perl, emacs, etc., where the system version may not be enough), or when something isn't easily fulfillable within Homebrew (java, osxfuse, tex, tuntap, x11, etc., where we need a binary installer), not for "I can install X from somewhere else so can I skip X".

**Comment by dunn** [comment]
FWIW some previous discussion at
- https://github.com/Homebrew/legacy-homebrew/pull/38789; and 
- https://github.com/Homebrew/legacy-homebrew/issues/44819

**Comment by pmyers88** [comment]
Understood. Thanks for the input!

**Comment by MikeMcQuaid** [comment]
I'm for this but will give it a wee while to see if other maintainers agree/disagree.

**Comment by MikeMcQuaid** [comment]
Note something that may or may not cause this to be useless: anything that's bottled and has a dependency on `node` will force the usage of the `node` formula as the build-time and run-time versions are not trivially interchangeable for requirements/dependencies.

**Comment by DomT4** [comment]
From my past experience on this, I think a special dependency here will end up causing Homebrew hassle personally, pretty much as neatly summarised by @zmwangx's comments.

I note that I actually proposed this multiple times in the past, particularly when the whole iojs situation went down, and I think time and Homebrew's Node stability has proven other maintainers here at the time who swatted away those PRs correct.

**Comment by MikeMcQuaid** [comment]
This repository was deprecated but we're reviewing a PR for this.

**Pull request closed without merging**
