### PR TITLE
004-better-tap-migrations.md

### PR DESCRIPTION
**Pull request by adidalal**
As requested by @MikeMcQuaid in Slack

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Makes sense to me. Will give people a little bit to chime in with other thoughts.

**Comment by UniqMartin** [comment]
I think the extension to `tap_migrations.json` itself is fine, but I wonder about the finer details of the implementation. I'm not sure how much of an issue this is for casks, as I'm not a Cask user, but for formulae this would need to tap into most of the formulae rename logic because we would need to preserve the old name in the cellar and in `opt` for various reasons (one being dynamic linkage to stuff at the old location) and move everything to the new name.

To me, this ultimately raises the question whether we should merge `tap_migrations.json` and `formulae_renames.json` into a single file if we start mixing the two. Both are actually about moving formulae (and more recently casks), it's just inter- and intra-tap moves and obviously the code behind the renames is a bit more involved because so much is tight to a stable formula name as an identifier (file system paths, dependencies, etc.).

**Comment by MikeMcQuaid** [comment]
@UniqMartin Perhaps, for now, we could allow this just for Cask as it's much simpler and barf if it's a formula?

**Comment by UniqMartin** [comment]
> Perhaps, for now, we could allow this just for Cask as it's much simpler and barf if it's a formula?

That would be fine by me. I just wanted to point out the potential complications and things worth considering if we think about extending this mechanism to formulae.

In any case, I'm happy about this proposal because it made me aware that the two mentioned migration mechanisms are conceptually very similar and could be unified, even though they differ quite a bit in their implementation. Thanks for that, @adidalal!

**Comment by adidalal** [comment]
Another, (related) issue that just came up was Cask renames - might it make sense to consider a `migrations.json` which handles the superset of both cases, for both Formulas and Casks?

**Comment by ilovezfs** [comment]
If cask renames within a given tap worked (apparently that's just never been worked on), isn't this achieved with the existing infrastructure by just doing a migration and then a rename? I guess simplifying things with a unified implementation is aesthetically more pleasing, but it seems to me there's actually nothing needed here other than basic intra-tap cask rename support and the functional goal is achieved.

**Comment by adidalal** [comment]
@ilovezfs That sounds reasonable to me, no sense overcomplicating things (and certainly, anything is better than the current non-exsistent rename support)

**Comment by MikeMcQuaid** [comment]
@adidalal Can you modify this just to be scoped to migrating things to Homebrew/cask for now and then I'll merge it? Thanks!

**Comment by adidalal** [comment]
Updated, thanks!

**Comment by MikeMcQuaid** [comment]
Thanks @adidalal!

**Pull request merged**
