### PR TITLE
invalid install option warnings

### PR DESCRIPTION
**Pull request by MatzFan**
As suggested by @zmwangx in Homebrew/brew#976

### CODE REVIEW

**Comment by zmwangx** [comment]
Fixed issue link for you.

**Comment by MatzFan** [comment]
Thanks @zmwangx. May be willing to do work on this myself, but can't see your test framework for the brew repo - just the bot for formulae. How do you test brew itself?

**Comment by zmwangx** [comment]
https://github.com/Homebrew/brew/tree/master/Library/Homebrew/test
https://bot.brew.sh/job/Brew%20Pull%20Requests/

**Comment by MatzFan** [comment]
thx

**Comment by MikeMcQuaid** [comment]
This was implemented.

**Pull request closed without merging**
